### ISSUE TITLE
HOL 2 - Configure SQL server to accept TCP connections

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/AppMigrationWorkshop#9]
## Expected Behavior
Web server is able to connect to SQL server

## Current Behavior
Web Server is unable to connect.

## Possible Solution
Enable TCP/IP as a network protocol for SQL

Enable the firewall rule for 1433
netsh advfirewall firewall add rule name = SQLPort dir = in protocol = tcp action = allow localport = 1433 remoteip = 10.0.0.0/22 profile = DOMAIN 

It looks like there is a script to configure this but it doesn't run.

**Comment by paulomarquesc** [comment]
Fixed with new template version. SQL 2008 R2 on Windows 2008 R2 image has a bug where there is a leftover of a Custom Script Extension there but that is in the file system and configured on Windows but the platform does not know about it because it is inside of the SYSPREPED image, so in the template I force a dumb execution of the extension, then another execution cleaning up the extension and then a third time with the real extension settings.
